version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: lab5_food_nginx
    ports:
      - "8082:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    container_name: lab5_food_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: lab5_food_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lab5_food_db
      MYSQL_USER: lab5_food_user
      MYSQL_PASSWORD: lab5_food_pass
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: lab5_food_adminer
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - db

volumes:
  db_data:
